sonar.projectKey=exam_er_backend
sonar.projectName=TaskList Backend
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=src/__tests__/**,src/server.ts
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.python.version=3
